USE [IFSDEV-ManualUpload]
GO

TRUNCATE TABLE [dbo].[FaBookPerObject]
GO
INSERT INTO [dbo].[FaBookPerObject]
           ([COMPANY]
           ,[BOOK_ID]
           ,[OBJECT_ID]
           ,[SALVAGE_VALUE]
           ,[DEPRECIATION_START_DATE]
           ,[START_YEAR]
           ,[START_PERIOD]
           ,[METHOD_ID]
           ,[FULLY_DEPRECIATED]
           ,[SET_DURING_IMPORT]
           ,[BUSINESS_USE]
           ,[DEDUCTION]
           ,[BONUS]
           ,[TAX_CREDIT]
           ,[TAX_CREDIT_REDUCTION]
           ,[ALLOW_AUT_SWITCH_STA_PRIN]
           ,[ESTIMATED_LIFE]
           ,[ALTERNATIVE_EST_LIFE])
SELECT [COMPANY]
      ,[BOOK_ID]
      ,[OBJECT_ID]
      ,[SALVAGE_VALUE]
      ,[DEPRECIATION_START_DATE]
      ,[START_YEAR]
      ,[START_PERIOD]
      ,'SL BP' [METHOD_ID]
      ,[FULLY_DEPRECIATED]
      ,[SET_DURING_IMPORT]
      ,[BUSINESS_USE]
      ,[DEDUCTION]
      ,[BONUS]
      ,[TAX_CREDIT]
      ,[TAX_CREDIT_REDUCTION]
      ,[ALLOW_AUT_SWITCH_STA_PRIN]
      ,[ESTIMATED_LIFE]
      ,[ALTERNATIVE_EST_LIFE]
  FROM [IFSDEV-ManualUpload].[dbo].[FaBookPerObject$]
GO


TRUNCATE TABLE [dbo].[FaImportDepreciation]
GO
INSERT INTO [dbo].[FaImportDepreciation]
           ([COMPANY]
           ,[OBJECT_ID]
           ,[BOOK_ID]
           ,[AMOUNT]
           ,[YEAR]
           ,[PERIOD]
           ,[TRANSACTION_REASON])
SELECT [COMPANY]
      ,[OBJECT_ID]
      ,[BOOK_ID]
      ,[AMOUNT]
      ,[YEAR]
      ,[PERIOD]
      ,[TRANSACTION_REASON]
  FROM [IFSDEV-ManualUpload].[dbo].[FaImportDepreciation$]
  WHERE [OBJECT_ID] IS NOT NULL
GO


TRUNCATE TABLE [dbo].[FaObjectTransaction]
GO
INSERT INTO [dbo].[FaObjectTransaction]
           ([COMPANY]
           ,[OBJECT_ID]
           ,[AMOUNT]
           ,[OBJECT_TRANSACTION_DATE]
           ,[EVENT_DATE]
           ,[BOOK_ID]
           ,[TRANSACTION_REASON])
SELECT  [COMPANY]
      ,[OBJECT_ID]
      ,[AMOUNT]      
	  ,[OBJECT_TRANSACTION_DATE]
	  ,convert(varchar(10), cast([EVENT_DATE] as datetime), 112)      
      ,[BOOK_ID]
      ,[TRANSACTION_REASON]
  FROM [IFSDEV-ManualUpload].[dbo].[FaObjectTransaction$]
  WHERE [OBJECT_ID] IS NOT NULL
GO

TRUNCATE TABLE [dbo].[FaObject]
GO
INSERT INTO [dbo].[FaObject]
           ([COMPANY]
           ,[OBJECT_ID]
           ,[DESCRIPTION]
           ,[VALID_FROM]
           ,[VALID_UNTIL]
           ,[MAIN_OBJECT_ID]
           ,[OBJECT_GROUP_ID]
           ,[FA_OBJECT_TYPE_DB]
           ,[ACQUISITION_DATE]
           ,[ACQUISITION_VALUE]
           ,[ACCOUNT]
           ,[CODE_B]
           ,[CODE_C]
           ,[CODE_D]
           ,[CODE_E]
           ,[CODE_F]
           ,[CODE_G]
           ,[CODE_H]
           ,[CODE_I]
           ,[CODE_J]
           ,[LOCATION]
           ,[OBJECT_OWNER]
           ,[SUPPLIER]
           ,[EXTERNAL_ID]
           ,[NOTE]
           ,[ATTRIBUTE_ACTIVE]
           ,[OVERRIDE_DEPRECIATION_PLAN]
           ,[INHERIT_DEPR_PLAN]
           ,[INHERIT_FINAL_DEPR_PERIOD]
           ,[START_YEAR]
           ,[START_PERIOD]
           ,[CHECK_NOTE]
           ,[IMPORT_DUMMY]
           ,[MTK_MODE]
           ,[OBJECT_CLASS]
           ,[SITE_ID]
           ,[TAG_NUMBER]
           ,[LOCATION_ID])
SELECT [COMPANY]
      ,[OBJECT_ID]
      ,[DESCRIPTION]
	  ,convert(varchar(10), cast([VALID_FROM] as datetime), 112)
      ,[VALID_UNTIL]
      ,[MAIN_OBJECT_ID]
      ,[OBJECT_GROUP_ID]
      ,[FA_OBJECT_TYPE_DB]
      ,convert(varchar(10), cast([ACQUISITION_DATE] as datetime), 112)
      ,[ ACQUISITION_VALUE ]
      ,[ACCOUNT]
      ,[CODE_B]
      ,[CODE_C]
      ,[CODE_D]
      ,[CODE_E]
      ,[CODE_F]
      ,[CODE_G]
      ,[CODE_H]
      ,[CODE_I]
      ,[CODE_J]
      ,[LOCATION]
      ,[OBJECT_OWNER]
      ,[SUPPLIER]
      ,[EXTERNAL_ID]
      ,[NOTE]
      ,[ATTRIBUTE_ACTIVE]
      ,[OVERRIDE_DEPRECIATION_PLAN]
      ,[INHERIT_DEPR_PLAN]
      ,[INHERIT_FINAL_DEPR_PERIOD]
      ,[START_YEAR]
      ,[START_PERIOD]
      ,[CHECK_NOTE]
      ,[IMPORT_DUMMY]
      ,[MTK_MODE]
      ,[OBJECT_CLASS]
      ,[SITE_ID]
      ,[TAG_NUMBER]
      ,[LOCATION_ID]
  FROM [IFSDEV-ManualUpload].[dbo].[FaObject$]
  WHERE [OBJECT_ID] IS NOT NULL
GO


TRUNCATE TABLE [dbo].[UsrDefinedBaseValue]
GO
INSERT INTO [dbo].[UsrDefinedBaseValue]
           ([COMPANY]
           ,[OBJECT_ID]
           ,[FROM_DATE]
           ,[TYPE_ID]
           ,[VALUE]
           ,[NOTE]
           ,[REG_DATE]
           ,[INDEX_ID])
SELECT [COMPANY]
      ,[OBJECT_ID]      
	  ,convert(varchar(10), cast([FROM_DATE] as datetime), 112)
      ,[TYPE_ID]
      ,[VALUE]
      ,[NOTE]
      ,[REG_DATE]
      ,[INDEX_ID]
  FROM [IFSDEV-ManualUpload].[dbo].[UsrDefinedBaseValue$]
  WHERE [OBJECT_ID] IS NOT NULL
GO


