-----[QmanControlPlan]
USE [IFSDEV-ManualUpload]
GO


TRUNCATE TABLE [QmanControlPlan]
GO

INSERT INTO [dbo].[QmanControlPlan]
		([CONTROL_PLAN_NO]
		,[CONTROL_PLAN_NO_AUX]
		,[CTRL_PLAN_REVISION_NO]
		,[PART_NO]
		,[CONTRACT]
		,[ENG_CHG_LEVEL]
		,[RESPONSIBLE_PERSON]
		,[CREATED_DATE]
		,[LAST_ACTIVITY_DATE]
		,[ACTIVED_DATE]
		,[ROUTING_REVISION]
		,[BOM_TYPE_DB]
		,[ROUTING_ALTERNATIVE_NO]
		,[CTRL_PLAN_PHASE_IN_DATE]
		,[CTRL_PLAN_PHASE_OUT_DAT]
		,[VENDOR_NO]
		,[NOTE_TEXT]
		,[ROWTYPE]
		,[ROWSTATE]
		,[USE_CATCH_UOM_DB]
		,TIPO)
-- Manufacturing - ALTERNATIVE
SELECT 
		'' CONTROL_PLAN_NO
		,rat.[PART_NO]+'*' CONTROL_PLAN_NO_AUX
		,1 [CTRL_PLAN_REVISION_NO]
		,rat.[PART_NO]
		,rat.[CONTRACT]
		,1 [ENG_CHG_LEVEL]
		,'*' [RESPONSIBLE_PERSON]
		,'2010-01-01' [CREATED_DATE]
		,'2010-01-01' [LAST_ACTIVITY_DATE]
		,'2010-01-01' [ACTIVED_DATE]
		,[ROUTING_REVISION]
		,[BOM_TYPE_DB]
		,[ALTERNATIVE_NO] [ROUTING_ALTERNATIVE_NO]
		,'2010-01-01'[CTRL_PLAN_PHASE_IN_DATE]
		,'1900-01-01'[CTRL_PLAN_PHASE_OUT_DAT]
		,'' [VENDOR_NO]
		,'' [NOTE_TEXT]
		,'QmanControlPlanManuf' [ROWTYPE]
		,'Active' [ROWSTATE]
		,'N' [USE_CATCH_UOM_DB] 
		,'*' 
FROM [RoutingAlternate] rat
WHERE [ALTERNATIVE_NO] = '*'

--Manufacturing - WITH OPTION
UNION ALL 
SELECT '' CONTROL_PLAN_NO
		,rat.[PART_NO]+'O' [CONTROL_PLAN_NO_AUX]
		,1 [CTRL_PLAN_REVISION_NO]
		,rat.[PART_NO]
		,rat.[CONTRACT]
		,1 [ENG_CHG_LEVEL]
		,'*' [RESPONSIBLE_PERSON]
		,'2010-01-01' [CREATED_DATE]
		,'2010-01-01' [LAST_ACTIVITY_DATE]
		,'2010-01-01' [ACTIVED_DATE]
		,[ROUTING_REVISION]
		,[BOM_TYPE_DB]
		,[ALTERNATIVE_NO] [ROUTING_ALTERNATIVE_NO]
		,'2010-01-01'[CTRL_PLAN_PHASE_IN_DATE]
		,'1900-01-01'[CTRL_PLAN_PHASE_OUT_DAT]
		,'' [VENDOR_NO]
		,'' [NOTE_TEXT]
		,'QmanControlPlanManuf' [ROWTYPE]
		,'Active' [ROWSTATE]
		,'N' [USE_CATCH_UOM_DB] 
		,'O' 
FROM [RoutingAlternate] rat
WHERE [ALTERNATIVE_NO] <> '*'




/***********Update [CONTROL_PLAN_NO]**************************************/
UPDATE [dbo].[QmanControlPlan]
SET [CONTROL_PLAN_NO] = case 
WHEN len([CONTROL_PLAN_NO_AUX]) > 12 THEN left([CONTROL_PLAN_NO_AUX], 9) + '01' + right([CONTROL_PLAN_NO_AUX], 1)
else [CONTROL_PLAN_NO_AUX] end;
GO

DECLARE @CONTROL_PLAN_NO VARCHAR(20);
DECLARE @CONTROL_PLAN_NO_AUX VARCHAR(20);
DECLARE @C_PLAN_NO_AUX VARCHAR;
DECLARE @LINE_ITEM_NO INT;
DECLARE @ID INT;

DECLARE main_curs 
CURSOR FOR 
	SELECT id, [CONTROL_PLAN_NO] 
	FROM [dbo].[QmanControlPlan]
	WHERE [CONTROL_PLAN_NO] in (select [CONTROL_PLAN_NO] from (SELECT [CONTROL_PLAN_NO],count(*) counter FROM [dbo].[QmanControlPlan] GROUP BY [CONTROL_PLAN_NO]) sdd WHERE counter > 1)
	ORDER BY [CONTROL_PLAN_NO], id;

SET @LINE_ITEM_NO = 1;
OPEN main_curs
FETCH NEXT FROM main_curs INTO @ID, @CONTROL_PLAN_NO
SET @CONTROL_PLAN_NO_AUX = @CONTROL_PLAN_NO;

while @@FETCH_STATUS = 0
BEGIN
UPDATE [QmanControlPlan]
SET [CONTROL_PLAN_NO] = left(@CONTROL_PLAN_NO, 9) + format(@LINE_ITEM_NO, '0#') + right(@CONTROL_PLAN_NO, 1)
WHERE [QmanControlPlan].ID = @ID;

SET @CONTROL_PLAN_NO_AUX = @CONTROL_PLAN_NO;
    FETCH NEXT FROM main_curs INTO @ID, @CONTROL_PLAN_NO;
IF @CONTROL_PLAN_NO_AUX <> @CONTROL_PLAN_NO
        SET @LINE_ITEM_NO = 1;
    ELSE
        SET @LINE_ITEM_NO = @LINE_ITEM_NO + 1;        
END
CLOSE main_curs
DEALLOCATE main_curs
GO