----PartMaster
SELECT
   PART_NO,
   DESCRIPTION,
   '' PROVIDE_DB,
   '' PART_CLASS,
   '' PART_RESPONSIBLE,
   '' STD_PLANNED,
   UNIT_CODE,
   LOT_TRACKING_CODE_DB,
   PART_MAIN_GROUP,
   ENG_SERIAL_TRACKING_CODE_DB,
   SERIAL_TRACKING_CODE_DB,
   SERIAL_RULE_DB,
   '' END_ITEM,
   '' PREFIX,
   '' SUFFIX,
   '' STD_NAME,
   INFO_TEXT,
   CONFIGURABLE_DB,
   CONDITION_CODE_USAGE_DB,
   POSITION_PART_DB,
   LOT_QUANTITY_RULE,
   SUB_LOT_RULE_DB,
   'N' IS_ENG_PART,
   '' MTK_MODE,
   '' DME_NAICS_CODE,
   MULTILEVEL_TRACKING_DB,
   INPUT_UNIT_MEAS_GROUP_ID,
   '' CATCH_UNIT_CODE,
   CATCH_UNIT_ENABLED,
   '' DME_PC_FLEX1,
   '' DME_PC_FLEX2,
   '' DME_PC_FLEX3,
   '' DME_PC_FLEX4,
   '' DME_PC_FLEX5,
   '' DME_PC_FLEX6,
   ALLOW_AS_NOT_CONSUMED,
   WEIGHT_NET,
   VOLUME_NET,
   UOM_FOR_WEIGHT_NET,
   UOM_FOR_VOLUME_NET,
   FREIGHT_FACTOR,
   STORAGE_WIDTH_REQUIREMENT,
   STORAGE_HEIGHT_REQUIREMENT,
   STORAGE_DEPTH_REQUIREMENT,
   STORAGE_VOLUME_REQUIREMENT,
   STORAGE_WEIGHT_REQUIREMENT,
   MIN_STORAGE_TEMPERATURE,
   MAX_STORAGE_TEMPERATURE,
   MIN_STORAGE_HUMIDITY,
   MAX_STORAGE_HUMIDITY,
   UOM_FOR_LENGTH,
   UOM_FOR_WEIGHT,
   UOM_FOR_VOLUME,
   UOM_FOR_TEMPERATURE,
   CAPACITY_REQ_GROUP_ID,
   CONDITION_REQ_GROUP_ID,
   CAPABILITY_REQ_GROUP_ID
FROM PART_CATALOG b
WHERE EXISTS (SELECT 1
   FROM INVENTORY_PART a
   WHERE a.PART_NO = b.part_no
   AND a.planner_buyer IN ('FLUX_FG','FLUX_RAW','FLUX_SE-FG','MEDIUM_FG','MEDIUM_SE-FG')
   AND a.CONTRACT = '10MTL'
   AND a.PART_STATUS = 'A')

----Inventory Part
SELECT
   a.PART_NO,
   a.CONTRACT,
   a.DESCRIPTION,
   a.UNIT_MEAS,
   a.TYPE_CODE,
   a.PLANNER_BUYER,
   a.PRIME_COMMODITY,
   a.SECOND_COMMODITY,
   a.ASSET_CLASS,
   a.PART_STATUS,
   a.ABC_CLASS,
   a.CYCLE_PERIOD,
   a.HAZARD_CODE,
   a.ACCOUNTING_GROUP,
   a.PART_PRODUCT_CODE,
   a.PART_PRODUCT_FAMILY,
   a.TYPE_DESIGNATION,
   a.DIM_QUALITY,
   '' WEIGHT_NET,
   a.CREATE_DATE,
   a.EXPECTED_LEADTIME,
   a.DURABILITY_DAY,
   '' SUPERSEDED_BY,
   a.SUPERSEDES,
   '' STD_NAME,
   '' EAN_NO,
   a.COUNTRY_OF_ORIGIN,
   a.CUSTOMS_STAT_NO,
   a.INTRASTAT_CONV_FACTOR,
   '' TECHNICAL_COORDINATOR,
   '' INVENTORY_VALUE,
   a.ESTIMATED_MATERIAL_COST,
   a.INVENTORY_VALUATION_METHOD,
   a.INVENTORY_PART_COST_LEVEL,
   a.ZERO_COST_FLAG,
   '' ACTUAL_COST_DB,
   a.PART_COST_GROUP_ID,
   a.NEGATIVE_ON_HAND_DB,
   a.SHORTAGE_FLAG,
   'A' PLANNING_METHOD,
   '0' MIN_ORDER_QTY,
   '0' MAX_ORDER_QTY,
   '0' MUL_ORDER_QTY,
   '0' SHRINKAGE_FAC,
   '' SHRINKAGE_ROUNDING,
   d.STD_ORDER_SIZE,
   d.SAFETY_STOCK,
   d.LOT_SIZE,
   d.ORDER_POINT_QTY,
   d.MAXWEEK_SUPPLY,
   '' ORDER_REQUISITION_DB,
   '' ENG_REVISION,
   '' ENG_CHG_LEVEL,
   '' ENG_REVISION_DESC,
   a.ENG_ATTRIBUTE,
   b.BACKFLUSH_PART_DB,
   b.PROCESS_TYPE,
   '' MTK_MODE,
   '' STD_PLANNED,
   a.FORECAST_CONSUMPTION_FLAG_DB,
   a.ONHAND_ANALYSIS_FLAG_DB,
   a.CYCLE_CODE_DB,
   '' QTY_PREDICTED_CONSUMPTION,
   a.NOTE_TEXT,
   a.QTY_CALC_ROUNDING,
   b.MANUF_ENGINEER,
   a.PURCH_LEADTIME,
   a.MANUF_LEADTIME,
   '' PROPOSAL_RELEASE_DB,
   c.AVERAGE_PURCHASE_PRICE,
   a.INPUT_UNIT_MEAS_GROUP_ID,
   a.SUPPLY_CODE_DB,
   a.EXT_SERVICE_COST_METHOD_DB,
   a.INVOICE_CONSIDERATION_DB,
   b.DENSITY,
   a.DOP_NETTING_DB,
   a.CATCH_UNIT_MEAS,
   b.MRP_CONTROL_FLAG_DB,
   a.STORAGE_WIDTH_REQUIREMENT,
   a.STORAGE_HEIGHT_REQUIREMENT,
   a.STORAGE_DEPTH_REQUIREMENT,
   a.STORAGE_VOLUME_REQUIREMENT,
   a.STORAGE_WEIGHT_REQUIREMENT,
   a.MIN_STORAGE_TEMPERATURE,
   a.MAX_STORAGE_TEMPERATURE,
   a.MIN_STORAGE_HUMIDITY,
   a.MAX_STORAGE_HUMIDITY,
   
   a.CF$_AIM_BASEHUOM AIM_BASEHUOM,
   a.CF$_AIM_COEF_METAL AIM_COEF_METAL,
   a.CF$_AIM_COEF_MFG AIM_COEF_MFG,
   a.CF$_AIM_FORMAT AIM_FORMAT,
   a.CF$_AIM_LABEL_ID AIM_LABEL_ID,
   a.CF$_AIM_PLANNING_METHOD AIM_PLANNING_METHOD,
   a.CF$_AIM_PRODUCTION_ALLOY AIM_PRODUCTION_ALLOY,
   a.CF$_ALLOYSPEC ALLOYSPEC,
   a.CF$_DIAMETER DIAMETER,
   a.CF$_FG_FORMAT FG_FORMAT,
   a.CF$_FLUX_TYPE FLUX_TYPE,
   a.CF$_LABEL_BOXES_LAYOUT LABEL_BOXES_LAYOUT,
   a.CF$_LABEL_DATE_FORMAT LABEL_DATE_FORMAT,
   a.CF$_LABEL_LAYOUT LABEL_LAYOUT,
   a.CF$_LABEL_UM LABEL_UM,
   a.CF$_LEADTYPE LEADTYPE,
   a.CF$_MARKET MARKET,
   a.CF$_MICRON MICRON,
   a.CF$_PER_FLUX PER_FLUX,
   a.CF$_PER_METAL PER_METAL,
   a.CF$_PROD_ALLOY1 PROD_ALLOY1,
   a.CF$_PROD_ALLOY2 PROD_ALLOY2,
   a.CF$_PROD_ALLOY3 PROD_ALLOY3,
   a.CF$_SHORT_PART_NO SHORT_PART_NO,
   a.CF$_UNIT_WEIGHT UNIT_WEIGHT,
   a.CF$_UPC UPC
FROM INVENTORY_PART_CFV a
LEFT JOIN MANUF_PART_ATTRIBUTE b ON a.CONTRACT = b.CONTRACT AND a.PART_NO = b.PART_NO
LEFT JOIN INVENTORY_PART_CONFIG c ON a.CONTRACT = c.CONTRACT AND a.PART_NO = c.PART_NO
LEFT JOIN INVENTORY_PART_PLANNING d ON a.CONTRACT = d.CONTRACT AND a.PART_NO = d.PART_NO
LEFT JOIN MANUF_PART_ATTRIBUTE e ON a.CONTRACT = e.CONTRACT AND a.PART_NO = e.PART_NO
WHERE a.planner_buyer IN ('FLUX_FG','FLUX_RAW','FLUX_SE-FG','MEDIUM_FG','MEDIUM_SE-FG')
AND a.CONTRACT = '10MTL'
AND a.PART_STATUS = 'A'



-----Sales Part
SELECT
   a.CATALOG_NO,
   a.CATALOG_TYPE_DB,
   a.CATALOG_DESC,
   a.PART_NO,
   a.CONTRACT,
   a.PRICE_UNIT_MEAS,
   a.CONV_FACTOR,
   a.PRICE_CONV_FACTOR,
   a.SALES_UNIT_MEAS,
   a.DATE_ENTERED,
   a.LIST_PRICE,
   a.SOURCING_OPTION,
   a.RULE_ID,
   a.SALES_PRICE_GROUP_ID,
   a.CATALOG_GROUP,
   a.DISCOUNT_GROUP,
   a.TAXABLE_DB,
   a.FEE_CODE,
   a.ACTIVEIND_DB,
   a.CLOSE_TOLERANCE,
   a.PACKAGE_TYPE,
   a.PROPOSED_PARCEL_QTY,
   '' PACKAGE_WEIGHT,
   a.WEIGHT_NET,
   a.WEIGHT_GROSS,
   a.VOLUME,
   a.PRINT_CONTROL_CODE,
   '' MTK_MODE,
   a.NOTE_TEXT,
   '' EAN_NO,
   a.MINIMUM_QTY,
   a.REPLACEMENT_PART_NO,
   a.DATE_OF_REPLACEMENT,
   a.CREATE_SM_OBJECT_OPTION_DB,
   a.EXPECTED_AVERAGE_PRICE,
   a.USE_SITE_SPECIFIC,
   a.PALLET_TYPE,
   a.PROPOSED_PALLET_QTY,
   a.CUST_WARRANTY_ID
   
FROM SALES_PART a
WHERE EXISTS (SELECT 1
   FROM INVENTORY_PART b
   WHERE a.PART_NO = b.part_no
   AND a.CONTRACT = b.CONTRACT
   AND b.planner_buyer IN ('FLUX_FG','FLUX_RAW','FLUX_SE-FG','MEDIUM_FG','MEDIUM_SE-FG')
   AND b.CONTRACT = '10MTL'
   AND b.PART_STATUS = 'A')

------Purchase PART
SELECT
   PART_NO,
   CONTRACT,
   DESCRIPTION,
   DATE_CRE,
   DEFAULT_BUY_UNIT_MEAS,
   STANDARD_PACK_SIZE,
   BUYER_CODE,
   technical_coordinator_id TECHNICAL_COORDINATOR ,
   STAT_GRP,
   CLOSE_TOLERANCE,
   OVER_DELIVERY_TOLERANCE,
   TAXABLE_DB,
   '' MTK_MODE,
   QC_CODE,
   NOTE_TEXT,
   QC_DATE   
FROM PURCHASE_PART a
WHERE EXISTS (SELECT 1
   FROM INVENTORY_PART b
   WHERE a.PART_NO = b.part_no
   AND a.CONTRACT = b.CONTRACT
   AND b.planner_buyer IN ('FLUX_FG','FLUX_RAW','FLUX_SE-FG','MEDIUM_FG','MEDIUM_SE-FG')
   AND b.CONTRACT = '10MTL'
   AND b.PART_STATUS = 'A')

-----PURCHASE_PART_SUPPLIER
SELECT
   PART_NO,
   CONTRACT,
   VENDOR_NO,
   VENDOR_PART_DESCRIPTION,
   VENDOR_PART_NO,
   PRICE_UNIT_MEAS,
   BUY_UNIT_MEAS,
   CONV_FACTOR,
   LIST_PRICE,
   CURRENCY_CODE,
   PRICE_CONV_FACTOR,
   '' EAN_NO,
   STANDARD_PACK_SIZE,
   'P' FLAG_VENDOR,
   STATUS_CODE,
   CONTACT,
   MINIMUM_QTY,
   VENDOR_MANUF_LEADTIME,
   STD_MULTIPLE_QTY,
   RECEIVE_CASE_DB,
   INSPECTION_CODE,
   SAMPLE_PERCENT,
   SAMPLE_QTY,
   '' MTK_MODE,
   PART_OWNERSHIP,
   EXTERNAL_SERVICE_ALLOWED_DB,
   INTERNAL_CONTROL_TIME,
   MULTISITE_PLANNED_PART_DB,
   FEE_CODE,
   SUPPLY_CONFIGURATION_DB,
   ORDERS_PRICE_OPTION_DB,
   QTY_CALC_ROUNDING,
   ASSORTMENT,
   ADDITIONAL_COST_AMOUNT,
   DISCOUNT,
   DELIVERY_PATTERN_ID   
FROM PURCHASE_PART_SUPPLIER a
WHERE EXISTS (SELECT 1
   FROM INVENTORY_PART b
   WHERE a.PART_NO = b.part_no
   AND a.CONTRACT = b.CONTRACT
   AND b.planner_buyer IN ('FLUX_FG','FLUX_RAW','FLUX_SE-FG','MEDIUM_FG','MEDIUM_SE-FG')
   AND b.CONTRACT = '10MTL'
   AND b.PART_STATUS = 'A')

---------------SalesPartCrossRef
SELECT
   a.CATALOG_NO,
   a.CUSTOMER_PART_NO,
   a.CUSTOMER_NO,
   a.CUSTOMER_UNIT_MEAS,
   a.CATALOG_DESC,
   a.CONTRACT,
   a.CONV_FACTOR,
   '' MTK_SOURCE
FROM SALES_PART_CROSS_REFERENCE a
INNER JOIN SALES_PART c ON a.CATALOG_NO = c.CATALOG_NO AND a.CONTRACT = c.CONTRACT
WHERE EXISTS (SELECT 1
   FROM INVENTORY_PART b
   WHERE c.PART_NO = b.part_no
   AND c.CONTRACT = b.CONTRACT
   AND b.planner_buyer IN ('FLUX_FG','FLUX_RAW','FLUX_SE-FG','MEDIUM_FG','MEDIUM_SE-FG')
   AND b.CONTRACT = '10MTL'
   AND b.PART_STATUS = 'A')

------------------Manufacture Structure HEADER
SELECT
   PART_NO,
   CONTRACT,
   '' ENG_REVISION,
   ENG_CHG_LEVEL,
   BOM_TYPE,
   '' ENG_CHG_ORDER,
   CREATE_DATE,
   '' CUST_WARRANTY_ID,
   NOTE_TEXT,
   '' MTK_MODE,
   '' ROWTYPE
FROM manuf_structure_head a
WHERE EXISTS (SELECT 1
   FROM INVENTORY_PART b
   WHERE a.PART_NO = b.part_no
   AND a.CONTRACT = b.CONTRACT
   AND b.planner_buyer IN ('FLUX_FG','FLUX_RAW','FLUX_SE-FG','MEDIUM_FG','MEDIUM_SE-FG')
   AND b.CONTRACT = '10MTL'
   AND b.PART_STATUS = 'A')

--------MANUF_STRUCTURE
SELECT
   PART_NO,
   CONTRACT,
   '' ENG_REVISION,
   ENG_CHG_LEVEL,
   ALTERNATIVE_NO,
   BOM_TYPE_DB,
   LINE_ITEM_NO,
   COMPONENT_PART,
   COMPONENT_CONTRACT,
   EFF_PHASE_IN_DATE,
   EFF_PHASE_OUT_DATE,
   QTY_PER_ASSEMBLY,
   SHRINKAGE_FACTOR,
   OPERATION_NO,
   CREATE_DATE,
   LAST_ACTIVITY_DATE,
   CONSUMPTION_ITEM,
   COMPONENT_SCRAP,
   '' MTK_MODE,
   ISSUE_TO_LOC,
   DRAW_POS_NO ,
   STD_PLANNED_ITEM,
   NOTE_TEXT,
   PHANTOM_CONSUME_DB,
   PROCEDURE_STEP
FROM MANUF_STRUCTURE a
WHERE EXISTS (SELECT 1
   FROM INVENTORY_PART b
   WHERE a.PART_NO = b.part_no
   AND a.CONTRACT = b.CONTRACT
   AND b.planner_buyer IN ('FLUX_FG','FLUX_RAW','FLUX_SE-FG','MEDIUM_FG','MEDIUM_SE-FG')
   AND b.CONTRACT = '10MTL'
   AND b.PART_STATUS = 'A')
