select a.CF$_BLANKET_ORDER Agrrement_No, 
       a.CF$_CUSTOMER_NO Customer, 
       CUSTOMER_INFO_API.Get_Name(a.CF$_CUSTOMER_NO) Customer_Name, 
       a.CF$_CUSTOMER_PO_NO CUSTOMER_PO_NO, 
       a.CF$_CONTRACT Site, 
       a.CF$_STATE Status, 
       a.CF$_BLANKET_TYPE Type, 
       a.CF$_AUTHORIZE_CODE Coordinator, 
       a.CF$_DEF_CURRENCY Currency, 
       a.CF$_SALESMAN_CODE Salesman, 
       a.CF$_VENDOR_NO Supplier, 
       SUPPLIER_INFO_API.Get_Name(a.CF$_VENDOR_NO) Supplier_Name, 
       a.CF$_NOTES Agreemant_Notes, 
       a.CF$_PURCH_NOTES Purchase_Agreemant_Notes,
       
       b.CF$_LINE_ITEM_NO LINE_ITEM_NO,         
       SALES_PART_api.Get_Part_No(b.CF$_CONTRACT, b.CF$_PART_NO) Sales_Part, 
       b.CF$_PART_NO Part_NO, 
       SALES_PART_api.Get_Catalog_Desc(b.CF$_CONTRACT, b.CF$_PART_NO) Part_Descr, 
       SALES_PART_API.Get_Sales_Unit_Meas(b.CF$_CONTRACT, b.CF$_PART_NO) Sales_UoM, 
       b.CF$_SALES_QTY SALES_QTY, 
       b.CF$_SALES_PRICE SALES_PRICE, 
       b.CF$_ORDER_NO CO_No, 
       CUSTOMER_ORDER_API.Get_State(b.CF$_ORDER_NO) CO_State, 
       b.CF$_ABNORMAL_CO ABNORMAL_CO, 
       b.CF$_DELIVERY_DATE DELIVERY_DATE, 
       b.CF$_FROM_DATE FROM_DATE, 
       b.CF$_TO_DATE TO_DATE, 
       b.CF$_MERGED MERGED, 
       ORDER_AIM_API.Get_COBlk_Line_SalesQty(b.CF$_BLANKET_ORDER,b.CF$_CONTRACT,b.CF$_LINE_ITEM_NO) Sales_Qty_Total, 
       CF$_SALES_QTY-ORDER_AIM_API.Get_COBlk_Line_SalesQty(b.CF$_BLANKET_ORDER,b.CF$_CONTRACT,b.CF$_LINE_ITEM_NO) Remaining_Qty, 
       Sales_Part_API.Get_Close_Tolerance(b.CF$_CONTRACT, b.CF$_PART_NO)
from CUSTOMER_BLANKET_CLV a
INNER JOIN CUSTOMER_BLANKET_LINE_CLV b ON a.CF$_BLANKET_ORDER = b.CF$_BLANKET_ORDER AND a.CF$_CONTRACT = b.CF$_CONTRACT
where a.CF$_CONTRACT = '&Contract'