UPDATE INVENTORY_TRANSFER_CLT 
SET cf$_status = 'Transfered'
WHERE cf$_status = 'New' AND 
EXISTS (SELECT 1 
   FROM  INVENTORY_TRANSACTION_HIST2
   WHERE INVENTORY_TRANSACTION_HIST2.CONTRACT = INVENTORY_TRANSFER_CLT.cf$_contract 
   AND INVENTORY_TRANSACTION_HIST2.PART_NO = INVENTORY_TRANSFER_CLT.cf$_from_part_no
   AND INVENTORY_TRANSACTION_HIST2.LOT_BATCH_NO = INVENTORY_TRANSFER_CLT.cf$_from_lot_batch_no
   AND INVENTORY_TRANSACTION_HIST2.TRANSACTION_CODE = 'NISS'
   AND INVENTORY_TRANSACTION_HIST2.quantity = INVENTORY_TRANSFER_CLT.CF$_QTY_TO_TRANSFER
   AND INVENTORY_TRANSACTION_HIST2.USERID = INVENTORY_TRANSFER_CLT.cf$_userid
   )
AND EXISTS (SELECT 1 
   FROM  INVENTORY_TRANSACTION_HIST2 
   WHERE INVENTORY_TRANSACTION_HIST2.CONTRACT = INVENTORY_TRANSFER_CLT.cf$_contract 
   AND INVENTORY_TRANSACTION_HIST2.PART_NO = INVENTORY_TRANSFER_CLT.cf$_to_part_no
   AND INVENTORY_TRANSACTION_HIST2.LOT_BATCH_NO = INVENTORY_TRANSFER_CLT.cf$_from_lot_batch_no
   AND INVENTORY_TRANSACTION_HIST2.TRANSACTION_CODE = 'NREC'
   AND INVENTORY_TRANSACTION_HIST2.quantity = INVENTORY_TRANSFER_CLT.CF$_QTY_TO_TRANSFER
   AND INVENTORY_TRANSACTION_HIST2.USERID = INVENTORY_TRANSFER_CLT.cf$_userid
   )
   
   
   
----------------- Update TRANSACTION_ID
DECLARE   
   CURSOR get_qaman IS
      SELECT objid, objversion
      FROM INVENTORY_TRANSFER_CLV 
      WHERE cf$_status = 'Transfered' 
      AND CF$_TRANSACTION_ID IS NULL;

   info_                VARCHAR2(32000);
   objid_               VARCHAR2(32000);
   objversion_          VARCHAR2(32000);
   attr_                VARCHAR2(26000);   
   TRANSACTION_ID_      NUMBER;
BEGIN
   
   FOR row_ IN get_qaman LOOP
      objid_ := row_.objid;
      objversion_ := row_.objversion;
      
      SELECT NVL(MAX(CF$_TRANSACTION_ID),0)+1 
      INTO TRANSACTION_ID_
      FROM INVENTORY_TRANSFER_CLV;
      
      Client_SYS.Clear_Attr(attr_);
      Client_SYS.Add_To_Attr('CF$_TRANSACTION_ID', TRANSACTION_ID_, attr_);      	  
      INVENTORY_TRANSFER_CLP.MODIFY__(info_, objid_, objversion_, attr_, 'DO');
      COMMIT;
   END LOOP;   
END;   